### ISSUE TITLE
Polygonal Editing Like in Google Earth

### ISSUE THREAD

**Issue by Daadan** [dCentralizedSystems/customer-support#35] opened 2020-07-10 00:09 UTC
Edit a polygonal area in Google Earth. it's a great UI/UX.

Employ same UI techniques to do in LCR UI.

I am trying to set a polygon for a long fence. It's torturous :-) It's really easy with Google Earth.

**Comment by Daadan** [comment] 2020-07-10 03:27
I took videos, but cannot upload them (attaching .mp4 files is not supported on GH).

**Comment by Daadan** [comment] 2020-07-10 03:30
It seems like the exclusion area in constrained to remain a quadrilateral, rather than an n-sided polygon, where  n > 4.

**Comment by georgechrysanthakopoulos** [comment] 2020-07-10 05:35
@Daadan you can only create 4 sided polygons. That is by design. Our video and text tutorials will cover that.

**Comment by georgechrysanthakopoulos** [comment] 2020-07-10 06:06
i am closing this,  I have created a focused internal issue to make creation of exclusion areas meant to trace fences, much easier. I will communicate when issue is resolved..

FYI, our DM issue tracker (which you used before) is here:

https://github.com/directedmachines/customer-support/issues

**Closed by georgechrysanthakopoulos** 2020-07-10 06:06 UTC
